development:
  solr:
    hostname: localhost
    port: 8982
    log_level: FINEST

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: FINEST

production:
  solr:
    hostname: solr01.soberlin.org
    port: 8080
    log_level: FINEST
