production:
  solr:
    hostname: solr.soberlin.org
    port: 8080
    log_level: INFO
    #pid_dir: '/home/deploy/app/shared/pids'
    path: /solr/core0
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: FINEST

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: FINEST
