production:
  solr:
    hostname: 178.79.175.179
    # solr01: 192.168.186.193
    port: 8080
    log_level: INFO
    #pid_dir: '/home/deploy/app/shared/pids'
    path: /solr/core0
    # read_timeout: 2
    # open_timeout: 0.5
    master_solr:
        hostname: 192.168.186.193
        port: 8080
        path: /solr/core0
    auto_commit_after_request: true

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: FINEST

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: FINEST
