---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: db01
  domain: soberlin.org
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-32726278
  image_type: m1.small
  image_id: ami-f2191786
  security_groups:
  - so_berlin_production_default
  - so_berlin_production_db01
  - so_berlin_production_db
  - so_berlin_production_mysql
  - so_berlin_production_mysql_master
  - so_berlin_production_collectd
  - so_berlin_production_monit
  external_host: ec2-54-216-42-111.eu-west-1.compute.amazonaws.com
  external_ip: 54.216.42.111
  internal_host: ip-10-33-173-120.eu-west-1.compute.internal
  internal_ip: 10.33.173.120
  zone: eu-west-1a
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: solr01
  domain: soberlin.org
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: solr
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-ac7363e6
  image_type: m1.small
  image_id: ami-f2191786
  security_groups:
  - so_berlin_production_default
  - so_berlin_production_solr01
  - so_berlin_production_solr
  - so_berlin_production_collectd
  - so_berlin_production_monit
  external_host: ec2-54-228-131-25.eu-west-1.compute.amazonaws.com
  external_ip: 54.228.131.25
  internal_host: ip-10-34-147-48.eu-west-1.compute.internal
  internal_ip: 10.34.147.48
  zone: eu-west-1a
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: web01
  domain: soberlin.org
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger_nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-c074648a
  image_type: m1.small
  image_id: ami-f2191786
  security_groups:
  - so_berlin_production_default
  - so_berlin_production_web
  - so_berlin_production_web_tools
  - so_berlin_production_web01
  - so_berlin_production_haproxy
  - so_berlin_production_app
  - so_berlin_production_passenger_nginx
  - so_berlin_production_collectd
  - so_berlin_production_monit
  external_host: ec2-54-216-15-206.eu-west-1.compute.amazonaws.com
  external_ip: 54.216.15.206
  internal_host: ip-10-34-173-196.eu-west-1.compute.internal
  internal_ip: 10.34.173.196
  zone: eu-west-1a
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
