---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: db01
  domain: soberlin.org
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-e4d5c4ae
  image_type: m1.small
  image_id: ami-f2191786
  security_groups:
  - so_berlin_production_default
  - so_berlin_production_db01
  - so_berlin_production_db
  - so_berlin_production_postgresql
  - so_berlin_production_postgresql_master
  - so_berlin_production_collectd
  - so_berlin_production_monit
  external_host: ec2-54-216-25-81.eu-west-1.compute.amazonaws.com
  external_ip: 54.216.25.81
  internal_host: ip-10-33-216-42.eu-west-1.compute.internal
  internal_ip: 10.33.216.42
  zone: eu-west-1a
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: solr01
  domain: soberlin.org
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: solr
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-acd4c5e6
  image_type: m1.small
  image_id: ami-f2191786
  security_groups:
  - so_berlin_production_default
  - so_berlin_production_solr01
  - so_berlin_production_solr
  - so_berlin_production_collectd
  - so_berlin_production_monit
  external_host: ec2-54-216-26-116.eu-west-1.compute.amazonaws.com
  external_ip: 54.216.26.116
  internal_host: ip-10-208-8-123.eu-west-1.compute.internal
  internal_ip: 10.208.8.123
  zone: eu-west-1c
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: web01
  domain: soberlin.org
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-ccd7c686
  image_type: m1.small
  image_id: ami-f2191786
  security_groups:
  - so_berlin_production_default
  - so_berlin_production_web
  - so_berlin_production_web_tools
  - so_berlin_production_web01
  - so_berlin_production_haproxy
  - so_berlin_production_app
  - so_berlin_production_passenger
  - so_berlin_production_apache
  - so_berlin_production_graphite_server
  - so_berlin_production_graphite_web
  - so_berlin_production_graylog_web
  - so_berlin_production_graylog_server
  - so_berlin_production_graylog_mongodb
  - so_berlin_production_mongodb
  - so_berlin_production_graylog_elasticsearch
  - so_berlin_production_elasticsearch
  - so_berlin_production_collectd
  - so_berlin_production_monit
  external_host: ec2-54-216-40-53.eu-west-1.compute.amazonaws.com
  external_ip: 54.216.40.53
  internal_host: ip-10-34-171-54.eu-west-1.compute.internal
  internal_ip: 10.34.171.54
  zone: eu-west-1a
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
